name: "Desplegar en servidor (Termux)"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código
        uses: actions/checkout@v4

      - name: Desplegar via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/firewall-Server
            git pull origin main
            pkill -f "python app.py" || true
            ./start_server.sh